### ISSUE TITLE
Callback when app is destroyed

### ISSUE THREAD

**Issue by trietbui85** [steveliles/Foredroid#1]
I would like to have a callback when app is destroyed. Is it possible?

**Comment by steveliles** [comment]
No, i'm afraid it isn't possible: the Android runtime simply kills apps when it needs to, without allowing any more of the app's code to run. For example, there's an onTerminate method in Application, but it will never be called in production (see comment):

```
/**
 * This method is for use in emulated process environments.  It will
 * never be called on a production Android device, where processes are
 * removed by simply killing them; no user code (including this callback)
 * is executed when doing so.
 */
public void onTerminate() {
}
```
