### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by francisconoriega** [steveliles/Foredroid#10]
Do you plan to add a license to your repo? Is it free for all? Non-commercial? What do you think of Apache 2?

**Comment by morriscodes** [comment]
Apache 2
https://github.com/steveliles/Foredroid/blob/master/Foredroid/build.gradle#L56

**Comment by francisconoriega** [comment]
Oh, I guess the standard (and where I was expecting to find it)  is to have a LICENSE file at the repo's root level.

Ex.
https://github.com/square/picasso/blob/master/LICENSE.txt
https://github.com/jenkinsci/jenkins/blob/master/LICENSE.txt
https://github.com/atom/atom/blob/master/LICENSE.md
https://github.com/nodejs/node/blob/master/LICENSE
https://github.com/Homebrew/brew/blob/master/LICENSE.txt

**Comment by steveliles** [comment]
I always forget about adding licenses. Fairly sure the Apache 2 in build.gradle was added automagically by intellij or something. That said, I'm good with Apache 2 if you guys are, and will add at project root.

**Comment by steveliles** [comment]
apache 2 FTW!
