### ISSUE TITLE
removeListener() cannot found

### ISSUE THREAD

**Issue by dipici** [steveliles/Foredroid#2]
Hi @steveliles,
thank you for this helpful class. But i get the error: 
"Cannot resolve method: removeListener(com.sjl.foreground.Foreground.Listener)"
Can fix this please?

Thank you

**Comment by steveliles** [comment]
There isn't a removeListener method. When you add a Listener it returns a Binding object - call `unbind` on that to remove the listener.

(btw. `removeListener` may come in a future update)

**Comment by steveliles** [comment]
... and to explain why the API is a little unusual: the implementation doesn't store any strong references to the `Listener` object - a defensive move to prevent memory leaks if you forget to unbind your listeners. This makes it awkward to implement a `removeListener` method, hence the `Binding`.
