### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by EscapeArtist** [steveliles/Foredroid#8]
Hi there.
I got a memory leak ( from Canary Leak ) coming from Foreground.current
I'm only doing this `Foreground.get(application).addListener(foregroundListener)`
in onCreate and unbinding in onDestroy.
Any ideas?

**Comment by steveliles** [comment]
I can spot one way that this could possibly happen - in the conditional branch starting at [line 122](https://github.com/steveliles/Foredroid/blob/master/Foredroid/src/main/java/com/sjl/foreground/Foreground.java#L222) when you go background `current` is not nullified, which probably qualifies as a leak.

I'm not actively working on any projects where I can look into this ... would be awesome if you're willing to try it out and raise a PR?

**Comment by EscapeArtist** [comment]
I made the change but do not have access to push to a new branch.

**Comment by steveliles** [comment]
@EscapeArtist cool, can you create a pull request?

**Comment by AlgoRyan** [comment]
Have experienced the same issue, and it is causing significant memory leaks. I have submitted a PR to resolve the issue, linked above.
